name: MUWarn
version: '0.0.1'
main: fr.ideeess.muwarn.MUWarn
api-version: '1.20'
commands:
  warn:
    description: Warn un joueur
  delwarn:
    description: Enlève le warn d'un joueur
  casier:
    description: Donne le casier d'un joueur
